import os



# CURRENT WORKING DIRECTORY
CWD = os.getcwd() + '\\'



# ESPACIO ENTRE COMPONENTES INTERFAZ INICIAL
ESPACIO_Y = 5
ESPACIO_X = 5

# CONSTANTES DE TAMAÑO DE LA INTERFAZ DE BUSQUEDA DE REGISTROS
MARCO_DE_BUSQUEDA_Y = 70
MARCO_DE_DATOS_Y = 350
ANCHO_MARCO_DATOS = 605
BOTON_MOD_X = 110
OCD = 3