import os



# CURRENT WORKING DIRECTORY
CWD = os.getcwd() + '\\'



# ESPACIO ENTRE COMPONENTES INTERFAZ INICIAL
ESPACIO_Y = 5
ESPACIO_X = 5

# CONSTANTES DE TAMAÑO DE LA INTERFAZ DE BUSQUEDA DE REGISTROS
MARCO_DE_BUSQUEDA_Y = 70
MARCO_DE_DATOS_Y = 450
ANCHO_MARCO_DATOS = 605
BOTON_MOD_X = 110
OCD = 7


# POSICIONES DE LA INFO EN LOS REGISTROS DEVUELTOS EN UNA BUSQUEDA
POS_NOMBRE_MASCOTA = 0
POS_ID_MASCOTA = 1
POS_NOMBRE_DUEÑO = 4
POS_DNI_DUEÑO = 5


# POSICIONES EN LA LISTA DE ENTRADAS (que tiene las todos los widgets que almacenan datos)
ENTRADA_NOMBRE_MASCOTA = 0
ENTRADA_ID_MASCOTA = 1
ENTRADA_RAZA = 2
ENTRADA_EDAD = 3
ENTRADA_DNI_DUENIO = 5 
ENTRADA_DNI_DUENIO2 = 9

# POSICIONES DEL REGISTRO DEVUELTO ObtenerDatosDueñoPorDni:
POS_REGISTRO = 0
POS_REGISTRO_ID = 1
POS_REGISTRO_DUEÑO = 0
POS_REGISTRO_EMAIL = 3
POS_REGISTRO_TEL = 4

# CONSTANTES GenerarEntryDueños
POS_DUEÑO = 0
POS_EMAIL = 1
POS_TEL = 2
POS_DUEÑO2 = 3
POS_EMAIL2 = 4
POS_TEL2 = 5